receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging: {}
  file/trace:
    path: /tmp/trace.json
    rotation:
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - file/trace
        - logging
